### ISSUE TITLE
Module not found: Can't resolve 'tweetnacl'

### ISSUE THREAD

**Issue by alistaircolling** [coinflow-labs-us/coinflow-react#1]
`    "@coinflowlabs/react": "^4.4.0",`

Getting this compile error:

```
 ⨯ ./node_modules/@coinflowlabs/react/build/esm/common/CoinflowUtils.js:5:1
Module not found: Can't resolve 'tweetnacl'
```

I think we just need to update package.json so `tweeetnacl` isn't an optional peer dependency

**Comment by bmeeder22** [comment]
Hey @alistaircolling `tweeetnacl` ~~is an **optional** peer dependency. Meaning that it is not required for the successful running of the package unless utilizing the features that specifically require it. Therefore this error must be from your bundler not supporting optional peer dependencies.~~

On second thought: I found a workaround which is compatible with more bundlers, that is in version 4.5.2
